services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      #$projectDir: '%kernel.project_dir%'


  Markocupic\BootstrapCarouselBundle\:
    resource: ../../
    exclude: ../../{DependencyInjection,Resources,Model}