services:
  _defaults:
    autowire: true
    autoconfigure: true

  Markocupic\BootstrapCarouselBundle\:
    resource: ../src/
    exclude:
      - ../src/ContaoManager/
      - ../src/DependencyInjection/
      - ../src/MarkocupicBootstrapCarouselBundle.php
